# -*- coding: utf-8 -*-
"""PrimeraPrueba.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1b0oQj_a2nbcwJgDl9phD6BlHB0vMvOGL
"""

#Librerias para trabajar con imagenes, números y matrices, hacer gráficos y mostrar imagenes
import cv2
import numpy as np
import matplotlib.pyplot as plt
from google.colab.patches import cv2_imshow

imagen = cv2.imread('/CancerOvario.png') #Leer imagen

imagen_RGB = cv2.cvtColor(imagen, cv2.COLOR_BGR2RGB) #Convertir de BGR a RGB

plt.imshow(imagen_RGB) #Mostrar imagen
plt.title('Imagen RGB') #Titulo
plt.show()

print("Dimensiones de la imagen: ", imagen.shape)
print("Tipo de dato de la imagen: ", imagen.dtype)

imagen_redimensionada = cv2.resize(imagen_RGB, (200,200))  #Dimensiones nuevas de la imagen

fig, axs = plt.subplots(1, 2, figsize=(8,4)) #Creamos espacio para mostrar imagenes (1 fila, 2 columnas)
axs[0].imshow(imagen_RGB)
axs[0].set_title('Imagen original')
axs[1].imshow(imagen_redimensionada)
axs[1].set_title('Imagen redimensionada')
plt.show()

peq_50 = cv2.resize(imagen_RGB, (0,0), fx=0.5, fy=0.5) #Hacemos la imagen más pequeña

fig, axs = plt.subplots(1, 2, figsize=(8,4))
axs[0].imshow(imagen_RGB)
axs[0].set_title('Imagen original')
axs[1].imshow(peq_50)
axs[1].set_title('Pequeño')
plt.show()