# -*- coding: utf-8 -*-
"""TerceraSesion.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1B5WeHDsgW1ru_3bq0pos2Hr7qKn4TQPG
"""

import cv2
import numpy as np
from matplotlib import pyplot as plt
import urllib.request
from google.colab.patches import cv2_imshow
import os

print("Descargando imagen de ejemplo")
url_raw = "https://raw.githubusercontent.com/Karencita17/Semillero-CancerOvario/a44f7c681cd6cb389e21b5b52f522c3e4ebf3b8b/Figura-3-Histopatologia-Infiltrado-dermico-superficial-y-profundo-de-Histiocitos.webp"
filename = "Figura-3-Histopatologia-Infiltrado-dermico-superficial-y-profundo-de-Histiocitos.webp"
urllib.request.urlretrieve(url_raw, filename)

# Re-Cargar imagen a color después de la descarga corregida
imagen_color = cv2.imread(filename)

# Re-Cargar imagen a escala de grises
imagen_gris = cv2.imread(filename, cv2.IMREAD_GRAYSCALE)

# 1 - Cargar una imagen

#Cargar imagen a color
imagen_color = cv2.imread(filename)

#Cargar imagen a escala de grises
imagen_gris = cv2.imread(filename, cv2.IMREAD_GRAYSCALE)

# 2 - Mostrar imagen

print("Imagen a color")
cv2_imshow(imagen_color)

print("Imagen a escala de grises")
cv2_imshow(imagen_gris)